---
- name: POST the AS3 declaration to the BIG-IP
  uri:
    url: "https://{{terraform_outputs_bigip.f5vm01_mgmt_public_ip.value}}:{{server_port}}/mgmt/shared/appsvcs/declare?async=true"
    method: POST
    user: "{{user}}"
    password: "{{password}}"
    validate_certs: no
    status_code: [200, 202]
    body: "{{ lookup('template', '~/automatingF5/ansible/templates/template_as3_base.j2') }}"
    
    body_format: json
  register: AS3_output
  tags:
    - buildApp

- name: Creating AS3 task variable for subsequent tasks
  set_fact:
    id: "{{AS3_output.json.id}}"
  tags:
    - buildApp

- name: Pause for 10 seconds before checking AS3 status
  ansible.builtin.pause:
    seconds: 10

- name: REST Call to check for the status of AS3 Declaration
  uri:
    url: "https://{{terraform_outputs_bigip.f5vm01_mgmt_public_ip.value}}:{{server_port}}/{{taskuri}}/{{id}}"
    method: GET
    return_content: yes
    status_code: [200, 202]
    user: "{{user}}"
    password: "{{password}}"
    force_basic_auth: yes
    validate_certs: no
  register: AS3_task_check
  until: AS3_task_check.json.results[0].message.find("in progress") == -1
  retries: 40
  delay: 15