---
- name: load vars from files downloaded from the App repository
  include_vars:
    files_matching: .yml
    dir: "~/automatingF5/ansible/playbooks/tmp/app-inputs/"
    name: apps
  tags:
    - buildApp

- name: Create Directory Structure for Site/Tenant
  file:
    path: "~/automatingF5/ansible/playbooks/tmp/appDeploy/{{item.value.app_locations.datacenter_name}}/{{item.value.tenant}}"
    state: directory
  with_dict: "{{apps}}"
  loop_control:
    label: "{{item}}"
  tags:
    - buildApp

- name: Create App AS3 json blob file(s) for each app
  template:
    src: "~/automatingF5/ansible/templates/{{item.value.app_template}}.j2"
    dest: "~/automatingF5/ansible/playbooks/tmp/appDeploy/{{item.value.app_locations.datacenter_name}}/{{item.value.tenant}}/{{item.value.app_name}}.json"
    mode: "preserve"
  with_dict: "{{ apps }}"
  loop_control:
    label: "{{item.key}}"
  tags:
    - buildApp

- name: Group all Application Files
  assemble:
    remote_src: False
    src: "~/automatingF5/ansible/playbooks/tmp/appDeploy/{{item.value.app_locations.datacenter_name}}/{{item.value.tenant}}/"
    dest: "~/automatingF5/ansible/playbooks/tmp/declarations/{{item.value.app_locations.datacenter_name}}-{{item.value.tenant}}_combined.yml"
    delimiter: ","
  with_dict: "{{apps}}"
  loop_control:
    label: "{{item}}"
  tags:
    - buildApp

- name: Retrive AS3 files to push
  command: "ls ~/automatingF5/ansible/playbooks/tmp/declarations/"
  register: dir_out
  tags:
    - buildApp
